const data = {
  products: [
    {
      id: 1,
      name: "Black Full Fit",
      slug: "black-full-fit",
      category: "Featured",
      image: "/images/apparel1.png",
      price: 120.0,
      countInStock: 10,
      rating: 3.5,
      brand: "AT collections",
      numReviews: 10,
      description:
        "Elevate your style with the Black Full Fit shirt by AT Collections. Crafted for comfort and fashion, this high-quality shirt is a must-have for any wardrobe.",
    },
    {
      id: 2,
      name: "AirPod",
      slug: "airpod",
      category: "Electronics",
      image: "/images/airpod.png",
      price: 90.0,
      countInStock: 80,
      brand: "Apple",
      rating: 4.0,
      numReviews: 10,
      description:
        "Immerse yourself in audio excellence with Apple's AirPods. These sleek, wireless earbuds deliver premium sound quality and a sophisticated matte black finish for a truly premium listening experience.high quality product, Experience audio excellence with Black AirPods. Sleek, stylish, and wireless, they deliver immersive sound, seamless connectivity, and a sophisticated matte black finish for a truly premium listening experience",
    },
    {
      id: 3,
      name: "Arm-Chair",
      slug: "arm-chair",
      category: "Featured",
      image: "/images/arm-chair.png",
      price: 115.0,
      countInStock: 15,
      brand: "Woody",
      rating: 3.0,
      numReviews: 14,
      description:
        "Experience the epitome of comfort with Woody's Arm-Chair. This high-quality piece offers a cozy spot to unwind and relax in style.",
    },
    {
      id: 4,
      name: "Bag Pack",
      slug: "bag-pack",
      category: "Others",
      image: "/images/bag-1.png",
      price: 65.0,
      countInStock: 5,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description:
        "Add a touch of sporty chic to your look with the Adidas Bag Pack. Designed for versatility, it features premium materials, ample storage, and the iconic Adidas logo.",
    },
    {
      id: 5,
      name: "Belt",
      slug: "belt",
      category: "Featured",
      image: "/images/belt.png",
      price: 65.0,
      countInStock: 0,
      brand: "Slikes Clothing",
      rating: 3.8,
      numReviews: 10,
      description:
        "Elevate your outfit with a high-quality belt from Slikes Clothing. This accessory adds a touch of style and sophistication to your look.",
    },
    {
      id: 6,
      name: "Black-Shirt",
      slug: "black-shirt",
      category: "Clothing",
      image: "/images/black-tshirt.png",
      price: 45.0,
      countInStock: 529,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description:
        "Puma's Black Shirt is a high-quality staple for your wardrobe. It combines style and comfort for a fashionable and relaxed look.",
    },
    {
      id: 7,
      name: "Addidas Bottle",
      slug: "addidas-bottle",
      category: "Others",
      image: "/images/bottle-1.png",
      price: 10.0,
      countInStock: 15,
      brand: "Addidas",
      rating: 3.5,
      numReviews: 10,
      description:
        "Stay hydrated in style with the Addidas Bottle. This high-quality product is a perfect companion for your active lifestyle.",
    },
    {
      id: 8,
      name: "Brown Hat",
      slug: "brown-hat",
      category: "Featured",
      image: "/images/brown-hat.png",
      price: 25.0,
      countInStock: 2,
      brand: "Trinity",
      rating: 4.0,
      numReviews: 10,
      description:
        "Enhance your look with the stylish Trinity Brown Hat. Crafted with care, this high-quality accessory adds flair to any outfit.",
    },
    {
      id: 9,
      name: "Brown Coat",
      slug: "brown-coat",
      category: "Clothing",
      image: "/images/brown-coat.png",
      price: 65.0,
      countInStock: 45,
      brand: "T&T collection",
      rating: 4.5,
      numReviews: 10,
      description:
        "Stay warm and fashionable with the T&T Collection's Brown Coat. This high-quality piece offers both style and functionality.",
    },
    {
      id: 10,
      name: "Lenovo Headset",
      slug: "lenovo-headset",
      category: "Featured",
      image: "/images/wireless-01.png",
      price: 55.0,
      countInStock: 5,
      brand: "Lenovo",
      rating: 4.5,
      numReviews: 1200,
      description:
        "Dive into a world of audio quality with the Lenovo Headset. This high-quality product promises a superior listening experience.",
    },
    {
      id: 11,
      name: "iPhone 14",
      slug: "iphone-14",
      category: "Featured",
      image: "/images/iphone-promax.png",
      price: 265.0,
      countInStock: 405,
      brand: "Apple",
      rating: 4.5,
      numReviews: 55788,
      description:
        "The Apple iPhone 14 is a technological masterpiece, blending innovation and elegance. With a powerful camera, stunning OLED display, and lightning-fast performance, it's your gateway to the future.",
    },
    {
      id: 12,
      name: "Nikon Camera",
      slug: "nikon-camera",
      category: "Electronics",
      image: "/images/camera-1.png",
      price: 165.0,
      countInStock: 95,
      brand: "Nikon",
      rating: 4.5,
      numReviews: 10,
      description:
        "Capture life's moments with the sleek and powerful Black Nikon Camera. High-resolution images, versatile shooting modes, and advanced autofocus make it perfect for stunning photos and videos.",
    },
    {
      id: 13,
      name: "PS5 Pad",
      slug: "ps5-pad",
      category: "Electronics",
      image: "/images/game-pad.png",
      price: 105.0,
      countInStock: 95,
      brand: "PSP",
      rating: 4.5,
      numReviews: 10,
      description:
        "Elevate your gaming experience with the PS5 Pad by PSP. This high-quality accessory enhances your gameplay and immersion.",
    },
    {
      id: 14,
      name: "Omel Glasses",
      slug: "omel-glasses",
      category: "Others",
      image: "/images/glasses.png",
      price: 70.0,
      countInStock: 5,
      brand: "Omel",
      rating: 4.0,
      numReviews: 10,
      description:
        "Embrace style and clarity with Omel Glasses. These high-quality eyewear pieces not only provide vision support but also add a touch of sophistication.",
    },
    {
      id: 15,
      name: "Addidas Hat",
      slug: "addidas-hat",
      category: "Others",
      image: "/images/hat-1.png",
      price: 45.0,
      countInStock: 25,
      brand: "Addidas",
      rating: 3.5,
      numReviews: 10,
      description:
        "Complete your look with the Addidas Hat. Crafted with care, this high-quality accessory is perfect for sports enthusiasts and fashion-forward individuals.",
    },
    {
      id: 16,
      name: "Iphone 12",
      slug: "iphone-12",
      category: "Electronics",
      image: "/images/iphone.png",
      price: 125.0,
      countInStock: 125,
      brand: "Apple",
      rating: 4.5,
      numReviews: 1780,
      description:
        "Experience Apple's legacy with the iPhone 12, a high-quality smartphone that combines performance and style seamlessly.",
    },
    {
      id: 17,
      name: "Diamond Earings",
      slug: "diamond-earings",
      category: "Jewelleries",
      image: "/images/jewellery-1.png",
      price: 300.0,
      countInStock: 105,
      brand: "AK Jewelleries",
      rating: 4.5,
      numReviews: 190,
      description:
        "Adorn yourself with elegance using AK Jewelleries' high-quality Diamond Earrings. These stunning pieces add a touch of luxury to any ensemble.",
    },
    {
      id: 18,
      name: "Diamond Necklace",
      slug: "diamond-necklace",
      category: "Jewelleries",
      image: "/images/jewellery-2.png",
      price: 156.0,
      countInStock: 85,
      brand: "AK Jewelleries",
      rating: 4.5,
      numReviews: 104,
      description:
        "AK Jewelleries' Diamond Necklace is a high-quality jewel that complements your style with its exquisite design and radiant beauty.",
    },
    {
      id: 19,
      name: "Trity XPS 14",
      slug: "trity-xps-14",
      category: "Electronics",
      image: "/images/laptop-1.png",
      price: 296.0,
      countInStock: 85,
      brand: "Trity",
      rating: 4.5,
      numReviews: 2,
      description:
        "Experience excellence with the Trity XPS 14 laptop. This high-quality electronic device offers top-notch performance and sleek design.",
    },
    {
      id: 20,
      name: "Blue Hoodie",
      slug: "blue-hoodie",
      category: "Clothing",
      image: "/images/mens-sweater.png",
      price: 76.0,
      countInStock: 85,
      brand: "Puma",
      rating: 3.0,
      numReviews: 10,
      description:
        "Puma's Blue Hoodie is a high-quality addition to your wardrobe. It's comfortable, stylish, and perfect for those who appreciate casual fashion.",
    },
    {
      id: 21,
      name: "Merie Heels",
      slug: "merie-heels",
      category: "Shoes",
      image: "/images/party-heels.png",
      price: 99.0,
      countInStock: 105,
      brand: "Merie Collection",
      rating: 4.5,
      numReviews: 70,
      description:
        "Step out in style with Merie Collection's high-quality heels. These fashionable shoes not only provide comfort but also add elegance to your look.",
    },
    {
      id: 22,
      name: "Samsung Galaxy S23",
      slug: "samsung-galaxy-s23",
      category: "Jewelleries",
      image: "/images/samsung.png",
      price: 196.0,
      countInStock: 205,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 1870,
      description:
        "Samsung's Galaxy S23 is a high-quality smartphone with cutting-edge features. It offers a top-tier camera, stunning display, and fast performance.",
    },
    {
      id: 23,
      name: "African Shirt",
      slug: "african-shirt",
      category: "Clothing",
      image: "/images/shirt-1.png",
      price: 86.0,
      countInStock: 85,
      brand: "GH Wears",
      rating: 4.5,
      numReviews: 490,
      description:
        "GH Wears' African Shirt is a high-quality clothing piece that reflects culture and style. It's perfect for those who appreciate unique fashion.",
    },
    {
      id: 24,
      name: "Nike Air",
      slug: "nike-air",
      category: "Shoes",
      image: "/images/shoe-1.png",
      price: 150.0,
      countInStock: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 1004,
      description:
        "Nike's Air sneakers are high-quality footwear designed for comfort and performance. Stay in style while staying active.",
    },
    {
      id: 25,
      name: "Formal Wear",
      slug: "formal-wear",
      category: "Shoes",
      image: "/images/shoe-2.jpg",
      price: 86.0,
      countInStock: 0,
      brand: "ATR",
      rating: 4.5,
      numReviews: 990,
      description:
        "ATR's Formal Wear shoes are the epitome of sophistication and style. These high-quality formal shoes add a touch of elegance to your attire, perfect for special occasions.",
    },

    {
      id: 26,
      name: "Nike Air Force",
      slug: "nike-air-force",
      category: "Shoes",
      image: "/images/shoe-3.jpg",
      price: 106.0,
      countInStock: 85,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Step up your footwear game with Nike's Air Force shoes. These high-quality sneakers offer a perfect blend of style, comfort, and performance.",
    },
    {
      id: 27,
      name: "Nike Air Force-Black",
      slug: "nike-air-force-black",
      category: "Shoes",
      image: "/images/shoe-4.jpg",
      price: 106.0,
      countInStock: 95,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Elevate your shoe collection with Nike's Air Force-Black. These high-quality sneakers are a fashion statement that complements your style.",
    },
    {
      id: 28,
      name: "Apple Series 1",
      slug: "apple-series-1",
      category: "Electronics",
      image: "/images/smart-watch-1.png",
      price: 186.0,
      countInStock: 185,
      brand: "Apple",
      rating: 4.5,
      numReviews: 1489,
      description:
        "Experience a blend of technology and style with the Apple Series 1 smartwatch. This high-quality accessory keeps you connected and fashionable.",
    },
    {
      id: 29,
      name: "Apple Series3",
      slug: "apple-series-3",
      category: "Electronics",
      image: "/images/smart-watch-2.png",
      price: 216.0,
      countInStock: 85,
      brand: "Apple",
      rating: 4.5,
      numReviews: 998,
      description:
        "Stay ahead with the Apple Series 3 smartwatch. This high-quality device is not just a timepiece but also a fashion statement.",
    },
    {
      id: 30,
      name: "Xio Watch 2",
      slug: "xio-watch-2",
      category: "Electronics",
      image: "/images/smart-watch-3.png",
      price: 96.0,
      countInStock: 15,
      brand: "Xiome",
      rating: 4.5,
      numReviews: 134,
      description:
        "Embrace smart style with Xiome's Xio Watch 2. This high-quality smartwatch combines functionality and fashion effortlessly.",
    },
    {
      id: 31,
      name: "Tecno Smart 1",
      slug: "tecno-smart-1",
      category: "Electronics",
      image: "/images/smart-watch-4.png",
      price: 56.0,
      countInStock: 18,
      brand: "Tecno",
      rating: 3.5,
      numReviews: 80,
      description:
        "Stay connected and stylish with Tecno Smart 1. This high-quality smartwatch is a perfect blend of technology and fashion.",
    },
    {
      id: 32,
      name: "Nike Shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/sneakers.png",
      price: 116.0,
      countInStock: 95,
      brand: "Nike",
      rating: 4.5,
      numReviews: 780,
      description:
        "Elevate your shoe game with Nike Shoes. These high-quality sneakers combine style and performance for an active and fashionable lifestyle.",
    },
    {
      id: 33,
      name: "Samsung Curved TV",
      slug: "samsung-curved-tv",
      category: "Electronics",
      image: "/images/tv-2.png",
      price: 216.0,
      countInStock: 178,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 7004,
      description:
        "Experience cinematic entertainment with Samsung's Curved TV. This high-quality television offers immersive viewing and stunning visuals.",
    },
    {
      id: 34,
      name: "W3 Headset",
      slug: "w3-headset",
      category: "Electronics",
      image: "/images/wireless-02.png",
      price: 96.0,
      countInStock: 185,
      brand: "Bing",
      rating: 4.5,
      numReviews: 10,
      description:
        "Upgrade your audio experience with W3 Headset by Bing. These high-quality wireless headphones provide premium sound quality for your listening pleasure.",
    },
    {
      id: 35,
      name: "W3 Headset Blue",
      slug: "w3-headset-blue",
      category: "Electronics",
      image: "/images/wireless-03.png",
      price: 96.0,
      countInStock: 25,
      brand: "Bing",
      rating: 4.5,
      numReviews: 10,
      description:
        "Dive into a world of audio excellence with the W3 Headset Blue by Bing. These high-quality wireless headphones deliver premium sound quality and style.",
    },
  ],
};
export default data;
