const data = {
  products: [
    {
      id: 1,
      name: "Black Full Fit",
      slug: "black-full-fit",
      category: "Featured",
      image: "/images/apparel1.jpg",
      price: 120.0,
      countInStock: 10,
      rating: 4.5,
      brand: "AT collections",
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 2,
      name: "Airpod",
      slug: "airpod",
      category: "Electronics",
      image: "/images/airpod.png",
      price: 90.0,
      countInStock: 80,
      brand: "Apple",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 3,
      name: "Arm-Chair",
      slug: "arm-chair",
      category: "Featured",
      image: "/images/arm-chair.png",
      price: 115.0,
      countInStock: 15,
      brand: "Woody",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: 4,
      name: "Bag Pack",
      slug: "bag-pack",
      category: "Others",
      image: "/images/bag-1.png",
      price: 65.0,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 5,
      name: "Belt",
      slug: "belt",
      category: "Featured",
      image: "/images/belt.png",
      price: 65.0,
      countInStock: 5,
      brand: "Slikes Clothing",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 6,
      name: "Black-Shirt",
      slug: "black-shirt",
      category: "Clothing",
      image: "/images/black-tshirt.png",
      price: 45.0,
      countInStock: 529,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 7,
      name: "Addidas Bottle",
      slug: "addidas-bottle",
      category: "Others",
      image: "/images/bottle-1.png",
      price: 10.0,
      countInStock: 15,
      brand: "Addidas",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 8,
      name: "Brown Hat",
      slug: "brown-hat",
      category: "Featured",
      image: "/images/brown-hat.png",
      price: 25.0,
      countInStock: 2,
      brand: "Trinity",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 9,
      name: "Brown Coat",
      slug: "brown-coat",
      category: "Clothing",
      image: "/images/brown-coat.png",
      price: 65.0,
      countInStock: 45,
      brand: "T&T collection",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 10,
      name: "Lenovo Headset",
      slug: "lenovo-headset",
      category: "Featured",
      image: "/images/lenovo-headset.jpg",
      price: 55.0,
      countInStock: 5,
      brand: "Lenovo",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 11,
      name: "Iphone 14",
      slug: "iphone-14",
      category: "Featured",
      image: "/images/iphone-promax.png",
      price: 265.0,
      countInStock: 405,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 12,
      name: "Canon Camera",
      slug: "canon-camera",
      category: "Electronics",
      image: "/images/camera-1.png",
      price: 165.0,
      countInStock: 95,
      brand: "Canon",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 13,
      name: "PS5 Pad",
      slug: "ps5-pad",
      category: "Electronics",
      image: "/images/game-pad.png",
      price: 105.0,
      countInStock: 95,
      brand: "PSP",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 14,
      name: "Omel Glasses",
      slug: "omel-glasses",
      category: "Others",
      image: "/images/glasses.png",
      price: 70.0,
      countInStock: 5,
      brand: "Omel",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 15,
      name: "Addidas Hat",
      slug: "addidas-hat",
      category: "Others",
      image: "/images/hat-1.jpeg",
      price: 45.0,
      countInStock: 25,
      brand: "Addidas",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 16,
      name: "Iphone 12",
      slug: "iphone-12",
      category: "Electronics",
      image: "/images/iphone.png",
      price: 125.0,
      countInStock: 125,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 17,
      name: "Diamond Earings",
      slug: "diamond-earings",
      category: "Jewelleries",
      image: "/images/jewellery-1.png",
      price: 300.0,
      countInStock: 105,
      brand: "AK Jewelleries",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 18,
      name: "Diamond Necklace",
      slug: "diamond-necklace",
      category: "Jewelleries",
      image: "/images/jewellery-2.png",
      price: 156.0,
      countInStock: 85,
      brand: "AK Jewelleries",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 19,
      name: "Trity XPS 14",
      slug: "trity-xps-14",
      category: "Electronics",
      image: "/images/laptop-1.png",
      price: 296.0,
      countInStock: 85,
      brand: "Trity",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 20,
      name: "Blue Hoodie",
      slug: "blue-hoodie",
      category: "Clothing",
      image: "/images/mens-sweater.png",
      price: 76.0,
      countInStock: 85,
      brand: "Puma",
      rating: 3.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 21,
      name: "Merie Heels",
      slug: "merie-heels",
      category: "Shoes",
      image: "/images/party-heels.png",
      price: 99.0,
      countInStock: 105,
      brand: "Merie Collection",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 22,
      name: "Samsung Galaxy S23",
      slug: "samsung-galaxy-s23",
      category: "Jewelleries",
      image: "/images/samsung.png",
      price: 196.0,
      countInStock: 205,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 23,
      name: "African Shirt",
      slug: "african-shirt",
      category: "Clothing",
      image: "/images/shirt-1.png",
      price: 86.0,
      countInStock: 85,
      brand: "GH Wears",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 24,
      name: "Nike Air",
      slug: "nike-air",
      category: "Shoes",
      image: "/images/shoe-1.jpg",
      price: 150.0,
      countInStock: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 25,
      name: "Formal Wear",
      slug: "formal-wear",
      category: "Shoes",
      image: "/images/shoe-2.jpg",
      price: 86.0,
      countInStock: 75,
      brand: "ATR",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 26,
      name: "Nike Air Force",
      slug: "nike-air-force",
      category: "Shoes",
      image: "/images/shoe-3.jpg",
      price: 106.0,
      countInStock: 85,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 27,
      name: "Nike Air Force-Black",
      slug: "nike-air-force-black",
      category: "Shoes",
      image: "/images/shoe-4.jpg",
      price: 106.0,
      countInStock: 95,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 28,
      name: "Apple Series 1",
      slug: "apple-series-1",
      category: "Electronics",
      image: "/images/smart-watch-1.png",
      price: 186.0,
      countInStock: 185,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 29,
      name: "Apple Series3",
      slug: "apple-series-3",
      category: "Electronics",
      image: "/images/smart-watch-2.png",
      price: 216.0,
      countInStock: 85,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 30,
      name: "Xio Watch 2",
      slug: "xio-watch-2",
      category: "Electronics",
      image: "/images/smart-watch-3.png",
      price: 96.0,
      countInStock: 15,
      brand: "Xiome",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 31,
      name: "Tecno Smart 1",
      slug: "tecno-smart-1",
      category: "Electronics",
      image: "/images/smart-watch-4.png",
      price: 56.0,
      countInStock: 18,
      brand: "Tecno",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 32,
      name: "Nike Shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/sneakers.png",
      price: 116.0,
      countInStock: 95,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 33,
      name: "Samsung Curved Tv",
      slug: "samsung-curved-tv",
      category: "Electronics",
      image: "/images/tv-2.png",
      price: 216.0,
      countInStock: 178,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 34,
      name: "W3 Headset",
      slug: "w3-headset",
      category: "Electronics",
      image: "/images/wireless-02.png",
      price: 96.0,
      countInStock: 185,
      brand: "Bing",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 35,
      name: "W3 Headset Blue",
      slug: "w3-headset-blue",
      category: "Electronics",
      image: "/images/wireless-03.png",
      price: 96.0,
      countInStock: 25,
      brand: "Bing",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
