// errorr handler
const getError = (error) => {
  return error.message;
};

export default getError;

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "DR Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern and Antarctic Lands",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islands",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syria",
  "São Tomé and Príncipe",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "United States Virgin Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

// const countries = {
//   1: "Afghanistan",
//   2: "Albania",
//   3: "Algeria",
//   4: "American Samoa",
//   5: "Andorra",
//   6: "Angola",
//   7: "Anguilla",
//   8: "Antarctica",
//   9: "Antigua and Barbuda",
//   10: "Argentina",
//   11: "Armenia",
//   12: "Aruba",
//   13: "Australia",
//   14: "Austria",
//   15: "Azerbaijan",
//   16: "Bahamas",
//   17: "Bahrain",
//   18: "Bangladesh",
//   19: "Barbados",
//   20: "Belarus",
//   21: "Belgium",
//   22: "Belize",
//   23: "Benin",
//   24: "Bermuda",
//   25: "Bhutan",
//   26: "Bolivia",
//   27: "Bosnia and Herzegovina",
//   28: "Botswana",
//   29: "Bouvet Island",
//   30: "Brazil",
//   31: "British Indian Ocean Territory",
//   32: "British Virgin Islands",
//   33: "Brunei",
//   34: "Bulgaria",
//   35: "Burkina Faso",
//   36: "Burundi",
//   37: "Cambodia",
//   38: "Cameroon",
//   39: "Canada",
//   40: "Cape Verde",
//   41: "Caribbean Netherlands",
//   42: "Cayman Islands",
//   43: "Central African Republic",
//   44: "Chad",
//   45: "Chile",
//   46: "China",
//   47: "Christmas Island",
//   48: "Cocos (Keeling) Islands",
//   49: "Colombia",
//   50: "Comoros",
//   51: "Cook Islands",
//   52: "Costa Rica",
//   53: "Croatia",
//   54: "Cuba",
//   55: "Curaçao",
//   56: "Cyprus",
//   57: "Czechia",
//   58: "DR Congo",
//   59: "Denmark",
//   60: "Djibouti",
//   61: "Dominica",
//   62: "Dominican Republic",
//   63: "Ecuador",
//   64: "Egypt",
//   65: "El Salvador",
//   66: "Equatorial Guinea",
//   67: "Eritrea",
//   68: "Estonia",
//   69: "Eswatini",
//   70: "Ethiopia",
//   71: "Falkland Islands",
//   72: "Faroe Islands",
//   73: "Fiji",
//   74: "Finland",
//   75: "France",
//   76: "French Guiana",
//   77: "French Polynesia",
//   78: "French Southern and Antarctic Lands",
//   79: "Gabon",
//   80: "Gambia",
//   81: "Georgia",
//   82: "Germany",
//   83: "Ghana",
//   84: "Gibraltar",
//   85: "Greece",
//   86: "Greenland",
//   87: "Grenada",
//   88: "Guadeloupe",
//   89: "Guam",
//   90: "Guatemala",
//   91: "Guernsey",
//   92: "Guinea",
//   93: "Guinea-Bissau",
//   94: "Guyana",
//   95: "Haiti",
//   96: "Heard Island and McDonald Islands",
//   97: "Honduras",
//   98: "Hong Kong",
//   99: "Hungary",
//   100: "Iceland",
//   101: "India",
//   102: "Indonesia",
//   103: "Iran",
//   104: "Iraq",
//   105: "Ireland",
//   106: "Isle of Man",
//   107: "Israel",
//   108: "Italy",
//   109: "Ivory Coast",
//   110: "Jamaica",
//   111: "Japan",
//   112: "Jersey",
//   113: "Jordan",
//   114: "Kazakhstan",
//   115: "Kenya",
//   116: "Kiribati",
//   117: "Kosovo",
//   118: "Kuwait",
//   119: "Kyrgyzstan",
//   120: "Laos",
//   121: "Latvia",
//   122: "Lebanon",
//   123: "Lesotho",
//   124: "Liberia",
//   125: "Libya",
//   126: "Liechtenstein",
//   127: "Lithuania",
//   128: "Luxembourg",
//   129: "Macau",
//   130: "Madagascar",
//   131: "Malawi",
//   132: "Malaysia",
//   133: "Maldives",
//   134: "Mali",
//   135: "Malta",
//   136: "Marshall Islands",
//   137: "Martinique",
//   138: "Mauritania",
//   139: "Mauritius",
//   140: "Mayotte",
//   141: "Mexico",
//   142: "Micronesia",
//   143: "Moldova",
//   144: "Monaco",
//   145: "Mongolia",
//   146: "Montenegro",
//   147: "Montserrat",
//   148: "Morocco",
//   149: "Mozambique",
//   150: "Myanmar",
//   151: "Namibia",
//   152: "Nauru",
//   153: "Nepal",
//   154: "Netherlands",
//   155: "New Caledonia",
//   156: "New Zealand",
//   157: "Nicaragua",
//   158: "Niger",
//   159: "Nigeria",
//   160: "Niue",
//   161: "Norfolk Island",
//   162: "North Korea",
//   163: "North Macedonia",
//   164: "Northern Mariana Islands",
//   165: "Norway",
//   166: "Oman",
//   167: "Pakistan",
//   168: "Palau",
//   169: "Palestine",
//   170: "Panama",
//   171: "Papua New Guinea",
//   172: "Paraguay",
//   173: "Peru",
//   174: "Philippines",
//   175: "Pitcairn Islands",
//   176: "Poland",
//   177: "Portugal",
//   178: "Puerto Rico",
//   179: "Qatar",
//   180: "Republic of the Congo",
//   181: "Romania",
//   182: "Russia",
//   183: "Rwanda",
//   184: "Réunion",
//   185: "Saint Barthélemy",
//   186: "Saint Helena, Ascension and Tristan da Cunha",
//   187: "Saint Kitts and Nevis",
//   188: "Saint Lucia",
//   189: "Saint Martin",
//   190: "Saint Pierre and Miquelon",
//   191: "Saint Vincent and the Grenadines",
//   192: "Samoa",
//   193: "San Marino",
//   194: "Saudi Arabia",
//   195: "Senegal",
//   196: "Serbia",
//   197: "Seychelles",
//   198: "Sierra Leone",
//   199: "Singapore",
//   200: "Sint Maarten",
//   201: "Slovakia",
//   202: "Slovenia",
//   203: "Solomon Islands",
//   204: "Somalia",
//   205: "South Africa",
//   206: "South Georgia",
//   207: "South Korea",
//   208: "South Sudan",
//   209: "Spain",
//   210: "Sri Lanka",
//   211: "Sudan",
//   212: "Suriname",
//   213: "Svalbard and Jan Mayen",
//   214: "Sweden",
//   215: "Switzerland",
//   216: "Syria",
//   217: "São Tomé and Príncipe",
//   218: "Taiwan",
//   219: "Tajikistan",
//   220: "Tanzania",
//   221: "Thailand",
//   222: "Timor-Leste",
//   223: "Togo",
//   224: "Tokelau",
//   225: "Tonga",
//   226: "Trinidad and Tobago",
//   227: "Tunisia",
//   228: "Turkey",
//   229: "Turkmenistan",
//   230: "Turks and Caicos Islands",
//   231: "Tuvalu",
//   232: "Uganda",
//   233: "Ukraine",
//   234: "United Arab Emirates",
//   235: "United Kingdom",
//   236: "United States",
//   237: "United States Minor Outlying Islands",
//   238: "United States Virgin Islands",
//   239: "Uruguay",
//   240: "Uzbekistan",
//   241: "Vanuatu",
//   242: "Vatican City",
//   243: "Venezuela",
//   244: "Vietnam",
//   245: "Wallis and Futuna",
//   246: "Western Sahara",
//   247: "Yemen",
//   248: "Zambia",
//   249: "Zimbabwe",
//   250: "Åland Islands",
// };

// fetch("https://restcountries.com/v3.1/all")
//   .then((data) => data.json())
//   .then((countries) => {
//     countries.map((country) => countriees.push(country.name.common));
//     console.log(countriees.sort().slice(-150));
//   });
